"""
Django settings for bocatapp project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+!)$=_j(u*@k8+v__b_cn1vbd8^+^w0+0ij195g$xdom%pnlh)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bocatapp',
    'administration',
    'customer',
    'seller',
    'bootstrap3',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'bocatapp.urls'
AUTH_USER_MODEL = 'bocatapp.User'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'bocatapp', 'templates'),
            os.path.join(BASE_DIR, 'administration', 'templates'),
            os.path.join(BASE_DIR, 'customer', 'templates'),
            os.path.join(BASE_DIR, 'seller', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bocatapp.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'bocatappdb',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',  # Or an IP Address that your DB is hosted on
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'es-ES'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DATE_INPUT_FORMATS = '%d-%m-%Y'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

# Deployment
# STATIC_ROOT = '/var/www/bocatapp.com/static'

# User files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

LOGIN_URL = '/login/'

###
# PAYSAFECARD
###
PAYSAFECARD_API_KEY = 'psc_Srilth8vrBdsb-lT-8bYNrHq5WAq9mE'
PAYSAFECARD_ENVIROMENT = 'TEST'
PAYSAFECARD_DEFAULT_CURRENCY = 'EUR'



###
# LOGGING
###
LOGGING = {
   'version': 1,
   'formatters': {
      'django': {
         'format': 'django: %(message)s',
       },
    },

    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },

   'handlers': {
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'stream': sys.stdout
        },
   },

   'loggers': {
      'bocatapp': {
            'handlers': ['console'],
            'propagate': True,
            'format': 'django: %(message)s',
            'level': 'DEBUG',
       },
    }


}


###
# EMAIL
###
ACCOUNT_ACTIVATION_DAYS=7

#EMAIL_HOST = "smtp.zoho.eu"
#EMAIL_USE_TLS = 1
#EMAIL_PORT = 587
#EMAIL_HOST_USER = 'info@bocatapp.com'
#EMAIL_HOST_PASSWORD = 'pA4TWcDDHiab'
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.zoho.eu'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'info@bocatapp.com'
EMAIL_HOST_PASSWORD = 'pA4TWcDDHiab'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = 'Bocatapp <info@bocatapp.com>'